notepad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('notes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.conf.urls import url
from . import views

app_name= "notes"

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^note/add/$', views.NoteCreate.as_view(), name='note-add'),

    url(r'^note/(?P<pk>[0-9]+)/$', views.NoteUpdate.as_view(), name='note-update'),

    url(r'^note/(?P<pk>[0-9]+)/delete/$', views.NoteDelete.as_view(), name='note-delete'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^logout/$', views.logout_view, name='logout'),


]

notes/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime


class Note(models.Model):
    note_title = models.CharField(max_length=250)
    brief = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(default=datetime.now)
    note_logo = models.FileField(blank= True, null=True)

    def get_absolute_url(self):
        return reverse('notes:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.note_title

notes/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

notes/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Note
from django.shortcuts import redirect

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'notes/home.html'
    context_object_name = 'all_notes'

    def get_queryset(self):
        return Note.objects.all()

class DetailView(generic.DetailView):
    model = Note
    template_name = 'notes/detail.html'

class NoteCreate(CreateView):
    model = Note
    fields = ['note_title', 'brief', 'body', 'note_logo']

class NoteUpdate(UpdateView):
    model = Note
    fields = ['note_title', 'brief', 'body', 'note_logo']

class NoteDelete(DeleteView):
    model = Note
    success_url = reverse_lazy('notes:home')

class UserFormView(View):
    form_class = UserForm
    template_name = 'notes/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned/ normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User Objects if credentioals are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('notes:home')
        return render(request, self.template_name, {'form': form})

def logout_view(request):
    logout(request)
    return redirect('notes:home')

notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Notepad</title>
    {% load static %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-indigo.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <style>
        html, body{
            background: lavender;
            min-height: 100%;
        }
        .container{
            padding-top: 20px;
        }

    </style>

</head>
<body>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">NotesCompanion</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="{% url 'notes:home' %}"><span class="glyphicon glyphicon-home"></span>  Home</a>
            <a class="mdl-navigation__link" href="{% url 'notes:note-add' %}"><span class="glyphicon glyphicon-plus"></span>  Add Note</a>
              {% if not user.is_authenticated %}
                <a class="mdl-navigation__link" href="{% url 'notes:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
                <!--<a class="mdl-navigation__link" href="/admin/"><span class="glyphicon glyphicon-lock"></span> Log In</a>-->
              {% else %}
                <a class="mdl-navigation__link" href="{% url 'notes:logout' %}"><span class="glyphicon glyphicon-off"></span> Log Out</a>
            {% endif %}
            <!-- <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a> -->
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">NotesCompanion</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{% url 'notes:home' %}"><span class="glyphicon glyphicon-home"></span>  Home</a>
            <a class="mdl-navigation__link" href="{% url 'notes:note-add' %}"><span class="glyphicon glyphicon-plus"></span>  Add Note</a>

            {% if not user.is_authenticated %}
                <a class="mdl-navigation__link" href="{% url 'notes:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
                <!--<a class="mdl-navigation__link" href="/admin/"><span class="glyphicon glyphicon-lock"></span> Log In</a>-->
            {% else %}
                <a class="mdl-navigation__link" href="{% url 'notes:logout' %}"><span class="glyphicon glyphicon-off"></span> Log Out</a>
            {% endif %}

            <!-- <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a> -->
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
              <div class="container">
                  {% block body %}
                  {% endblock %}
              </div>
        </div>

      </main>
    </div>
</body>
</html>

notes/templates/notes/detail.html
{% extends 'notes/base.html' %}

{% block body %}
	<style>
		.mdl-card{
			width:100%;
			margin: 20px;
		}

	</style>
    <div class="mdl-card">
    	<div class="mdl-card__title">
    		<h1>{{ note.note_title }}</h1>
    	</div>

    	<div class="mdl-card__supporting-text">
    		<h6>{{ note.date }}</h6>
		    <p>{{ note.body }}</p>
    	</div>
    </div>
{% endblock %}

notes/templates/notes/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

notes/templates/notes/home.html
{% extends 'notes/base.html' %}

{% block body %}
    <ul>
        {% for note in all_notes %}
            <!-- Square card -->
			<style>
			@media only screen (max width:400px){.demo-card-square.mdl-card {
			  width: 100%;
			  height: 320px;
			  margin-top: 10px;
			  display: inline-flex;
				}}
            .mdl-card__actions{
                display: inline-flex;
            }
            form{
                width:30%;
            }
			.demo-card-square > .mdl-card__title {
			  color: #fff;
                {% if note.note_logo %}
                    background: url('{{ note.note_logo.url }}') bottom right 15% no-repeat darkgray;;
                {% endif %}
                background: darkgray;
            }
			</style>

			<div class="demo-card-square mdl-card mdl-shadow--2dp">
			  <div class="mdl-card__title mdl-card--expand">
			    <h2 class="mdl-card__title-text">{{ note.note_title }}</h2>
			  </div>
			  <div class="mdl-card__supporting-text">
			    {{ note.brief }}
			  </div>
			  <div class="mdl-card__actions mdl-card--border">
			    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="/{{ note.pk }}">
			      View
			    </a>
                  <form action="{% url 'notes:note-update' note.pk%}" method="get">
                      {% csrf_token %}
                      <button class="mdl-button mdl-js-button mdl-button--accent"><span class="glyphicon glyphicon-pencil"></span></button>
                  </form>
                  <form action="{% url 'notes:note-delete' note.pk%}" method="post">
                      {% csrf_token %}
                      <button class="mdl-button mdl-js-button mdl-button--accent"><span class="glyphicon glyphicon-trash"></span></button>
                  </form>
			  </div>
			</div>
        {% endfor %}
    </ul>
{% endblock %}

notes/templates/notes/note_form.html
{% extends 'notes/base.html' %}

{% block body %}

<div class="container">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'notes/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

notes/templates/notes/registration_form.html
{% extends 'notes/base.html' %}

{% block body %}

<div class="container">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'notes/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}